/**
 * Prebuild gate: synthesize the demo portfolio, or refuse to.
 *
 * package.json runs this before every `next build`. It used to run the
 * synthesizer unconditionally, which meant a live build would spend ~20
 * seconds inventing 80,035 loans and then ship the 2.7 MB result inside the
 * bundle -- fabricated exposures sitting in a production artifact, waiting
 * for one forgotten filter to surface them.
 *
 * Now the flag decides. JANA_DEMO=1 builds the artifact; anything else skips
 * it and actively removes a stale one, so a live build cannot inherit a
 * portfolio generated by an earlier demo build in the same working tree.
 * That last part matters more than it looks: the artifact is gitignored and
 * long-lived, so "I built the demo yesterday" is exactly how it would end up
 * in a live bundle.
 *
 * Written as .mjs so it runs under plain node with no TypeScript toolchain,
 * which keeps the gate working even if the dev dependencies are not
 * installed in the build environment.
 */

import { existsSync, rmSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = join(repoRoot, "lib/data/precomputed-portfolio.json.gz");
const isDemo = process.env.JANA_DEMO === "1";

if (!isDemo) {
  console.log(
    "[precompute-guard] JANA_DEMO is not set — building WITHOUT the demo layer.",
  );
  if (existsSync(artifact)) {
    rmSync(artifact);
    console.log(
      "[precompute-guard] Removed a stale precomputed portfolio left by an " +
        "earlier demo build. A live bundle must not carry synthesized loans.",
    );
  }
  console.log(
    "[precompute-guard] The loan book will be empty until core-banking " +
      "import is available. This is expected.",
  );
  process.exit(0);
}

console.log("[precompute-guard] JANA_DEMO=1 — synthesizing the demo portfolio.");
const result = spawnSync(
  "npx",
  ["tsx", "scripts/precompute-portfolio.ts"],
  { cwd: repoRoot, stdio: "inherit", shell: process.platform === "win32" },
);

if (result.status !== 0) {
  console.error(
    "[precompute-guard] Synthesis failed. Refusing to continue: a demo build " +
      "without its portfolio would fall back to synthesizing on first " +
      "request, which is the ~20s cold start the precompute exists to avoid.",
  );
  process.exit(result.status ?? 1);
}
